"""empty message

Revision ID: d1aaec6e5794
Revises: db1a7d1e458e
Create Date: 2024-02-24 22:41:32.117902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1aaec6e5794'
down_revision = 'db1a7d1e458e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_character', sa.Integer(), nullable=True),
    sa.Column('id_planet', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_character'], ['character.id'], ),
    sa.ForeignKeyConstraint(['id_planet'], ['planet.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('favorites_planet')
    op.drop_table('favorites_character')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites_character',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_user', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_character', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_character'], ['character.id'], name='favorites_character_id_character_fkey'),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], name='favorites_character_id_user_fkey'),
    sa.PrimaryKeyConstraint('id', name='favorites_character_pkey')
    )
    op.create_table('favorites_planet',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_user', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_planet', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_planet'], ['planet.id'], name='favorites_planet_id_planet_fkey'),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], name='favorites_planet_id_user_fkey'),
    sa.PrimaryKeyConstraint('id', name='favorites_planet_pkey')
    )
    op.drop_table('favorites')
    # ### end Alembic commands ###
